import projectsImages from "../../assets/projectsImages";

const projects = [
  {
    id: 1,
    title: "The Power of PostgreSQL + PostGIS",
    category: ["postgresql/postgis", "all"],
    image: projectsImages.oze,
    desc: "Implementation of a GIS system in renewable energy projects",
    pathGitHub:
      "https://github.com/hroblesdiez/gis_system_in_renewable_energy_projects",
  },
  {
    id: 2,
    title: "Polish Power Plants",
    category: ["qgis", "javascript", "all"],
    image: projectsImages.powerplants,
    desc: "Web showing the Power Plants in Poland",
    pathDemo: "https://hroblesdiez.github.io/polish_power_plants/",
    pathGitHub: "https://github.com/hroblesdiez/polish_power_plants",
  },
  {
    id: 3,
    title: "Polish crop production",
    category: ["qgis", "restapi", "all"],
    image: projectsImages.apigus,
    desc: "A simple web app to see the Polish production and performance of crops from 1999 to 2022",
    pathDemo: "https://hroblesdiez.github.io/api_GUS/",
    pathGitHub: "https://github.com/hroblesdiez/api_GUS",
  },
  {
    id: 4,
    title: "Geologic map",
    category: ["microstation", "all"],
    image: projectsImages.mapa_geologico,
    desc: "Geologic map for the Geological and Mining Institute of Spain",
    pathDemo:
      "https://www.researchgate.net/profile/Augusto-Rodriguez-Garcia-2/publication/333619573_Mapa_Geomorfologico_de_Espana_150000_n263_Celanova/links/5cf7a76a299bf1fb1859cd14/Mapa-Geomorfologico-de-Espana-150000-n263-Celanova.pdf",
  },
  {
    id: 5,
    title: "Coolfood",
    category: ["sql", "all"],
    image: projectsImages.sql,
    desc: "Analyzing the performance of a delivery food company querying using SQL a MS SQL Server database",
    pathGitHub: "https://github.com/hroblesdiez/coolfood",
  },
  {
    id: 6,
    title: "Optical vs Radar Optical Satelite Images",
    category: ["python", "all"],
    image: projectsImages.optical_radar_images,
    desc: "Correlation between NDVI from optical and radar satellite images",
    pathGitHub:
      "https://github.com/hroblesdiez/optical_vs_radar_satellite_images",
  },
  {
    id: 7,
    title: "Web scrapping and Python analysis",
    category: ["python", "all"],
    image: projectsImages.handball,
    desc: "Project to predict the winner of the 2022 European Men's Handball Championship",
    pathGitHub:
      "https://github.com/hroblesdiez/2022_european_men_handball_championship",
  },
  {
    id: 8,
    title: "Power BI analysis",
    category: ["powerbi", "all"],
    image: projectsImages.bicilink,
    desc: "A Sales Dashboard Power BI showing the performance of a bicycle company",
    pathGitHub: "https://github.com/hroblesdiez/bicilink",
  },
  {
    id: 9,
    title: "Portfolio",
    category: ["reactjs", "all"],
    image: projectsImages.portfolio,
    desc: "Humberto's portfolio",
    pathDemo: "https://humberto-robles.netlify.app/",
    pathGitHub: "https://github.com/hroblesdiez/portfolio-humberto",
  },
  {
    id: 10,
    title: "Recipe App",
    category: ["reactjs", "restapi", "all"],
    image: projectsImages.recipes,
    desc: "Web application to find recipes according to your nedds",
    pathDemo: "https://recipe-app-liart.vercel.app/",
    pathGitHub: "https://github.com/hroblesdiez/recipe-app",
  },
  {
    id: 11,
    title: "Online shopping",
    category: ["javascript", "all"],
    image: projectsImages.shopping,
    desc: "A shop cart developed in Vanilla Javascript",
    pathDemo: "https://the-best-experience-in-online-shoppin.netlify.app/",
    pathGitHub: "https://github.com/hroblesdiez/online-shopping",
  },
  {
    id: 12,
    title: "Nice photos",
    category: ["javascript", "restapi", "all"],
    image: projectsImages.nicePictures,
    desc: "A simple API integration to find a nice photo",
    pathDemo: "https://find-beautiful-photos.netlify.app/",
    pathGitHub: "https://github.com/hroblesdiez/API-integration",
  },
  {
    id: 13,
    title: "Control Expenses App",
    category: ["javascript", "all"],
    image: projectsImages.expenses,
    desc: "A simple app to control all your expenses",
    pathDemo: "https://control-your-expenses.netlify.app/",
    pathGitHub: "https://github.com/hroblesdiez/control-expenses",
  },
];

export default projects;
