import projectsImages from "../../assets/projectsImages";

const projects = [
    {
        id: 1,
        title: "Recipe App",
        category: ["reactjs", "api", "all"],
        image: projectsImages.recipes,
        desc: "Web application to find recipes according to your nedds",
        pathDemo: "https://recipe-app-liart.vercel.app/",
        pathGitHub: "https://github.com/hroblesdiez/recipe-app",
    },
    {
        id: 2,
        title: "Online shopping",
        category: ["javascript", "ecommerce", "all"],
        image: projectsImages.shopping,
        desc: "A shop cart developed in Vanilla Javascript",
        pathDemo: "https://the-best-experience-in-online-shoppin.netlify.app/",
        pathGitHub: "https://github.com/hroblesdiez/online-shopping",
    },
    {
        id: 3,
        title: "Control Expenses App",
        category: ["javascript", "all"],
        image: projectsImages.expenses,
        desc: "A simple app to control all your expenses",
        pathDemo: "https://control-your-expenses.netlify.app/",
        pathGitHub: "https://github.com/hroblesdiez/control-expenses",
    },
    {
        id: 4,
        title: "Library App",
        category: ["php", "all"],
        image: projectsImages.library,
        desc: "A pretty simple Library web application to load, edit and delete books",
        pathDemo: "https://your-library-store.000webhostapp.com/",
        pathGitHub: "https://github.com/hroblesdiez/library",
    },
    {
        id: 5,
        title: "Nice photos",
        category: ["javascript", "api", "all"],
        image: projectsImages.nicePictures,
        desc: "A simple API integration to find a nice photo",
        pathDemo: "https://find-beautiful-photos.netlify.app/",
        pathGitHub: "https://github.com/hroblesdiez/API-integration",
    },
    {
        id: 6,
        title: "Medical House",
        category: ["wordpress", "all"],
        image: projectsImages.medical,
        desc: "A WordPress developed theme from scratch that takes care about people health",
        pathDemo: "https://medicalhouse.server2.trinchera.dev/",
        pathGitHub: "https://github.com/hroblesdiez/boilerplate",
    },
    {
        id: 7,
        title: "Dogger",
        category: ["wordpress", "all"],
        image: projectsImages.dogger,
        desc: "A WordPress developed theme from scratch showing wonderful dogs",
        pathDemo: "https://dogger.server2.trinchera.dev/",
        pathGitHub: "https://github.com/hroblesdiez/dogger",
    },
    {
        id: 8,
        title: "Sprystore",
        category: ["wordpress", "ecommerce", "all"],
        image: projectsImages.sprystore,
        desc: "A Woocommerce shop theme developed from scratch",
        pathDemo: "https://sprystore.server1.trinchera.dev/",
        pathGitHub: "https://github.com/hroblesdiez/SpryStore",
    },
    {
        id: 9,
        title: "Portfolio",
        category: ["reactjs", "all"],
        image: projectsImages.portfolio,
        desc: "Humberto's portfolio",
        pathDemo: "https://humberto-robles.netlify.app/",
        pathGitHub: "https://github.com/hroblesdiez/portfolio-humberto",
    },
    {
        id: 10,
        title: "Gutenberg block",
        category: ["wordpress", "plugins"],
        image: projectsImages.gutblocks,
        desc: "A simple Gutenberg block to show the staff in your company",
        pathGitHub: "https://github.com/hroblesdiez/gut-blocks",
    },
];

export default projects;
